FROM cimg/python:3.12

USER root

RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    default-mysql-client \
    nodejs; \
    npm install yarn -g; \
    rm -rf /var/lib/apt/lists/*

COPY --chown=app:app \
  ./source/pyproject.toml ./source/poetry.lock* \
  ./source/package.json source/yarn.lock \
  /home/circleci/project/

USER circleci

RUN poetry install --no-root --no-interaction --no-ansi
RUN yarn install
