FROM darthjee/weave-base:0.0.1


COPY --chown=app:app \
  ./source/pyproject.toml ./source/poetry.lock* \
  ./source/package.json source/yarn.lock \
  /home/app/app/

RUN poetry install --no-root --no-interaction --no-ansi
RUN yarn install